### PR TITLE
Added a wrapper for Application by default, for ease of including custom...

### PR DESCRIPTION
**Pull request by theahindle**
... traits etc.

### CODE REVIEW

**Comment by dsimkus** [comment]
If you don't do SilexApp, it fatals because two classes are called Application

**Comment by dsimkus** [comment]
you could do, extends \Silex\Application perhaps :)

**Comment by theahindle** [comment]
Sure but you could do `class Application extends \Silex
Application`

**Comment by dsimkus** [comment]
Whatever floats your boat, they use SilexApp in their docs!

**Pull request merged**
